name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    
      - name: 🦑 Personal metrics
        # See action.yml for all options
        uses: lowlighter/metrics@latest
        with:
            # Your GitHub token
            token: ${{ secrets.METRICS_TOKEN }}
            # Options
            user: saforem2
            template: classic
            base: header, activity, community, repositories, metadata, habits
            config_timezone: America/Chicago
            plugin_activity: yes
            plugin_activity_days: 14
            plugin_activity_filter: all
            plugin_activity_limit: 10
            plugin_activity_timestamps: yes
            plugin_activity_visibility: all
            plugin_introduction: yes
            plugin_introduction_title: yes
            plugin_isocalendar: yes
            plugin_isocalendar_duration: full-year
            plugin_languages: yes
            plugin_languages_colors: github
            plugin_languages_ignored: Jupyter Notebook, html, css, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
            plugin_languages_limit: 12
            plugin_languages_indepth: yes
            plugin_languages_details: lines, bytes-size
            plugin_lines: yes
            plugin_stars: yes
            plugin_stars_limit: 5
            plugin_achievements: yes
            plugin_achievements_only: polyglot, stargazer, sponsor, deployer, member, maintainer, developer, scripter, packager, explorer, infographile, manager
            plugin_achievements_display: compact
            plugin_achievements_threshold: X
            plugin_habits: yes
            plugin_habits_facts: no
            plugin_habits_charts: yes
            plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
            plugin_notable: yes
            plugin_notable_indepth: yes
            plugin_notable_repositories: yes
            plugin_projects: yes
            plugin_projects_repositories: lowlighter/metrics/projects/1
            plugin_projects_descriptions: yes
            plugin_stargazers: yes
            plugin_traffic: yes
            plugin_tweets: yes
            plugin_tweets_attachments: yes
            plugin_tweets_limit: 2
            plugin_tweets_user: .user.login
            plugin_music: yes
            plugin_music_provider: lastfm  # Use Last.fm as provider
            plugin_music_mode: recent      # Set plugin mode
            plugin_music_limit: 4          # Limit to 4 entries
            plugin_music_user: .user.login # Use same username as GitHub login
            plugin_music_token: ${{ secrets.LASTFM_API_KEY }}
